name: disoriza
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  iconsax_plus: ^1.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-Regular.ttf
          weight: 400
        - asset: assets/fonts/InterTight-Medium.ttf
          weight: 500
        - asset: assets/fonts/InterTight-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterTight-Bold.ttf
          weight: 700
