name: disoriza
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  animated_snack_bar: ^0.4.0
  cached_network_image: ^3.4.0
  card_loading: ^0.3.2
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  equatable: ^2.0.5
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  fpdart: ^1.1.0
  iconsax_plus: ^1.0.0
  page_transition: ^2.1.0
  scroll_to_index: ^3.0.1
  supabase_flutter: ^2.8.0
  timeago: ^3.7.0

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: InterTight
      fonts:
        - asset: assets/fonts/InterTight-Regular.ttf
          weight: 400
        - asset: assets/fonts/InterTight-Medium.ttf
          weight: 500
        - asset: assets/fonts/InterTight-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterTight-Bold.ttf
          weight: 700
